version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "reshalo"
      POSTGRES_USER: "reshalo"
      POSTGRES_PASSWORD: "1234"

  admin:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  reshalo_service:
    image: santygo77/reshalo:latest
    ports:
      - "8080:8082"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/reshalo'
      SPRING_DATASOURCE_USERNAME: 'reshalo'
      SPRING_DATASOURCE_PASSWORD: '1234'
      SERVER_PORT: "8082"
      SPRING_PROFILES_ACTIVE: 'tikhon'

networks:
  net:
    driver: bridge


