server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false'
    password: "password"
    username: "user"
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
logging:
  level:
    ru.danilkaspirin.reshalo.application: debug